name: Sync Main Branch Site Content to Staging

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
    paths:
      - '_pages/**'
      - '_posts/**'
      - '_working_notes/**'
      - '_photography/**'
      - '_portfolio/**'
      - '_data/**'
      - 'assets/images/**'
      - 'assets/photography/**'
      - '_config.yml'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history needed to access both branches
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Switch to staging branch
        run: |
          git checkout staging
      
      - name: Sync content from main branch
        run: |
          # Remove existing content to ensure clean sync
          rm -rf _pages _photography _portfolio _posts _data _working_notes
          
          # Checkout content directories from main
          git checkout main -- _pages _photography _portfolio _posts _data _working_notes _config.yml
          
          # Sync content assets if they exist
          if git ls-tree main assets/images >/dev/null 2>&1; then
            rm -rf assets/images
            git checkout main -- assets/images
          fi
          
          if git ls-tree main assets/photography >/dev/null 2>&1; then
            rm -rf assets/photography
            git checkout main -- assets/photography
          fi
      
      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes to sync"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git status --porcelain
          fi
      
      - name: Commit and push to staging
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "Sync content from main - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin staging
      
      - name: Summary
        run: |
          if [ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]; then
            echo "✅ Content successfully synced to staging branch"
          else
            echo "ℹ️ Staging branch already up to date"
          fi